export var Global = {
    urlBackEnd: 'https://8gf95lar45.execute-api.us-east-1.amazonaws.com/prod/',
    urlCertif: 'http://localhost:5000/api/cert',
    //urlSucursales: 'https://rf7ipa27na.execute-api.us-east-1.amazonaws.com/prod/sucursales',
    TIMER_OFF: 1500,
    OK: 200,
    AGREGAR_SUCURSAL: 'Agregar Sucursal',
    EDITAR_SUCURSAL: 'Editar Sucursal',
    Factura:{
    Moneda:'MXN',
    Version:'4.0',
    TipoCambio:1,
    TipoComprobante:'I',
    Exportacion:'01',
    CondicionesPago:'Un solo pago',
    MetodoPago:'PUE',
    ImpuestoIVA:'002',
    ImpuestoISR:'001',
    Tasa:'Tasa',
    Cuota:'Cuota',
    TasaOCuotaIVA:'0.160000',
    TasaOCuotaISR:'0.000000',
    ObjectoImpuesto:'02',
    FP_EFECTIVO:'01',
    FP_TRANSFERENCIA:'03',
    FP_TARJETA:'04',
    IVA:0.16,
    FACTOR_DIV:1.16
  },
    DECIMAL_FIXED:2,
};